<a href="https://colab.research.google.com/github/Parinita-Jain/DeepLearning/blob/main/tensorflow_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
Deep learning frameworks
 
 
TensorFlow is an open-source software library for dataflow programming across a range of tasks. 
It is a symbolic math library that is used for machine learning applications like neural networks. Tensorflow provides both low and high-level APIs.
Keras is an open-source neural network library written in Python. It is capable of running on top of TensorFlow. 
It is designed to enable fast experimentation with deep neural networks. Keras provides only high-level APIs.
The Tensorflow version that we will use is 2.0. 
The major difference between Tensorflow 1.0 and 2.0 is that version 2.0 has adopted the Keras API as a standard method of creating neural networks.
Other Deep learning frameworks are PyTorch, Theano, etc.  
'''

'\nDeep learning frameworks\n \n \nTensorFlow is an open-source software library for dataflow programming across a range of tasks. \nIt is a symbolic math library that is used for machine learning applications like neural networks. Tensorflow provides both low and high-level APIs.\nKeras is an open-source neural network library written in Python. It is capable of running on top of TensorFlow. \nIt is designed to enable fast experimentation with deep neural networks. Keras provides only high-level APIs.\nThe Tensorflow version that we will use is 2.0. \nThe major difference between Tensorflow 1.0 and 2.0 is that version 2.0 has adopted the Keras API as a standard method of creating neural networks.\nOther Deep learning frameworks are PyTorch, Theano, etc.  \n'

In [ ]:
# !pip install tensorflow.----------for installing into localsystem

In [ ]:
'''
Google Collab allows one to change runtime to GPU and TPU, which is suitable for training neural networks. 

'''

In [2]:
import tensorflow as tf

# Import and check the Tensorflow version.

In [3]:
print(tf.__version__)

2.9.2


In [4]:
#Creating Constants using tf.constant() method.
c1=tf.constant(3)
c2=tf.constant([10,20])
c3=tf.constant([[10,20],[30,40]])


'''
A constant created is of type Tensor. A Tensor object can be a scalar, vector, or matrix.

'''

In [6]:
print(f"C1: {c1}\nC2 : {c2}\nC3 : \n{c3}")

C1: 3
C2 : [10 20]
C3 : 
[[10 20]
 [30 40]]


In [7]:
"""
Printing the NumPy version of the tensor object using numpy() function.
"""

print(f"C1: {c1.numpy()}\nC2 : {c2.numpy()}\nC3 : \n{c3.numpy()}")

C1: 3
C2 : [10 20]
C3 : 
[[10 20]
 [30 40]]


In [8]:
"""
A new value cannot be assigned to a Tensorflow constant.
"""

print(type(c1))
c1=4
type(c1)

<class 'tensorflow.python.framework.ops.EagerTensor'>


int

In [9]:
"""
A new value can be assigned only through operations.
"""

c1=tf.constant(3)
print(c1)
c1=c1+4
print(c1)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [ ]:
"""
Creating Variables using tf.Variable() method.
"""

In [13]:
v1=tf.Variable(3)
v2=tf.Variable([10,20])
v3=tf.Variable([[10,20],[30,40]])

In [14]:
print(f"v1: {v1}\nv2 : {v2}\nv3 : \n{v3}")

v1: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>
v2 : <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>
v3 : 
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>


In [15]:
"""
Tensorflow variables are of type Variable object. A new value can be assigned to a tensorflow variable using the assign() method.
"""
print(type(v1))
print(v1.assign(4))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=4>
